### ISSUE TITLE
Error when not having a slash

### ISSUE THREAD

**Issue by Srlion** [HFQR/xitca-web#955]
Hey there, thank you for this amazing framework!

This errors because no slash at start of the "api" route:
```rust
use xitca_web::{handler::handler_service, route::get, App};

fn main() -> std::io::Result<()> {
	async fn test() -> &'static str {
		"hey"
	}

	let nested = App::new().at("/create", get(handler_service(test)));
	let app = App::new().at("api", nested);

	app.serve().bind("localhost:8000")?.run().wait()
}
```

```
2024-02-24, 10:13:51 PM  INFO xitca_server::net: 25: Started Tcp listening on: Some(127.0.0.1:8000)
thread 'xitca-server-worker-0' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'xitca-server-worker-1' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-5' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-2' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-4' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-3' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-7' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-6' panicked at thread '/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rsxitca-server-worker-8:' panicked at 88/home/.cargo/registry/src/index.crates.io-6f17d22bb
a15001f/xitca-http-0.3.0/src/util/service/router.rs::8854::
54called `Result::unwrap()` on an `Err` value: InvalidCatchAll:

called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-9' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-10' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-11' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-12' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-13' panicked at thread '/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rsxitca-server-worker-14:' panicked at 88/home/.cargo/registry/src/index.crates.io-6f17d22
bba15001f/xitca-http-0.3.0/src/util/service/router.rs::5488:
:called `Result::unwrap()` on an `Err` value: InvalidCatchAll54
:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-15' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-http-0.3.0/src/util/service/router.rs:88:54:
called `Result::unwrap()` on an `Err` value: InvalidCatchAll
thread 'xitca-server-worker-shared-scope' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-server-0.1.0/src/server/mod.rs:135:17:
a scoped thread panicked
^C2024-02-24, 10:13:55 PM  INFO xitca_server::server::future: 130: Signal Int received.
thread 'main' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xitca-server-0.1.0/src/server/mod.rs:199:39:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

**Comment by fakeshadow** [comment]
We depend on `matchit` for path based routing and in this case when app nested the path of "api" would implicitly rewritten to "api/*x" causing the error. Related issue https://github.com/ibraheemdev/matchit/issues/42

Though a fork of said crate renamed as `xitca-route` is what being used in this workspace I would like to keep the behavior consistent between the fork and original when it's possible. I would look into a port when the change has been made to resolve related issue.

**Comment by fakeshadow** [comment]
#978 would allow nesting with a no leading slash path.

That said `http` crate is used in `xitca` to represent a http request path and it carries a leading slash by default. So in order to successfully match against no leading slash path you have to override `http`'s behavior and remove the leading slash. Example:

```rust
use xitca_web::{
    handler::handler_service,
    http::{uri::PathAndQuery, Uri},
    route::get,
    service::Service,
    App, WebContext,
};

fn main() -> std::io::Result<()> {
    async fn test() -> &'static str {
        "hey"
    }

    let nested = App::new().at("/create", get(handler_service(test)));
    let app = App::new().at("api", nested).enclosed_fn(middleware);

    app.serve().bind("localhost:8080")?.run().wait()
}

// middleware for removing leading slash from http::Uri.
async fn middleware<S, Res, Err>(s: &S, mut ctx: WebContext<'_>) -> Result<Res, Err>
where
    S: for<'r> Service<WebContext<'r>, Response = Res, Error = Err>,
{
    let uri = ctx.req().uri();

    let mut uri_new = Uri::builder();

    if let Some(auth) = uri.authority() {
        uri_new = uri_new.authority(auth.clone());
    }

    if let Some(scheme) = uri.scheme() {
        uri_new = uri_new.scheme(scheme.clone());
    }

    if let Some(path) = uri.path_and_query() {
        let path = path.to_string();
        uri_new = uri_new.path_and_query(PathAndQuery::try_from(&path.as_str()[1..]).unwrap());
    }

    *ctx.req_mut().uri_mut() = uri_new.build().unwrap();
    s.call(ctx).await
}
```
